language: java
jdk:
- oraclejdk8
script:
- mvn clean -B package
deploy:
  provider: releases
  api_key:
    secure: DJbeZSrDlbnn5qthmO9q4p6z1DiBAZsds1AKmBLJ3BRvi7W4UnX6+5obPjmK3EU7M2iS4dg/Toil6iAVQfBBnRlyTJM+P5sTmm77JIT5RfHyH67G+QT6uz4LgkOLfk0yD6ixJlpQGogykzaQYRVE96LtBABmQ/mna15C4pBQm0ch8+K1xT3n1lwlXCVWf/s//ntBAOfvq05dFO4jPEqlsThABnrI3lRhAQ+3lzKLBx0cFrcwnPJHX/hAC8WZaUA0ZuksmVsQQ6VyKtzWSMX/mXVMrXI7wXD7lzWMjIq8iwTJg2NSIS2pH6H603ukeGa6xrVZMFTvwl0synWon49WPWfADhQYVYVYQo3H0owtnfhtc6Qh52KaeV2SPcY+AoqagYp2jHRaSwStURwNAP7weDAF3eQ9KM2KR5tiMtzqyIGOljInTKsOHA0CFXkvsbavk2JqpHv0VQzjIImmFOx4KdWCylycvRi9OAm2dpFT3TUY4czf8r8vUZooeB0lKUXfjpPETKKmazmf8XDJSCMJbbuMMwaVq5fNV06GXkQhmyjDJ1ybv0gBZzm/h9qBnYkDF0pUvX4M3H1vS4wSQbfSkH5Ne6ha/TG7ekqEbEO6tucFFgROnhGzQp56J0+i9urSseCdziFBtjPvFB6R6cLDOHcPIpquIOclAShuARU1kwY=
  file: target/dotwebstack-theatre-legacy*.jar
  skip_cleanup: true
  file_glob: true
  on:
    repo: dotwebstack/dotwebstack-theatre-legacy
    tags: true
